version: '3.8' # It's good practice to specify a version

services:
  redis:
    image: "redis:alpine"
    container_name: lightbox_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # This command tells Redis to start and require the password 'simplenes'
    command: ["redis-server", "--requirepass", "simplenes"]
    restart: always

  web:
    build: .
    container_name: lightbox_web
    command: gunicorn --workers 3 --bind 0.0.0.0:5102 app:app --access-logfile - --error-logfile - --log-level info
    volumes:
      - ./static/uploads:/app/static/uploads
      # - ./static/thumbnails:/app/static/thumbnails # Uncomment if you use this
    ports:
      - "5102:5102"
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: lightbox_celery_worker
    command: celery -A app.celery worker -l info -Q celery --concurrency=4
    volumes:
      - ./static/uploads:/app/static/uploads
    env_file:
      - ./.env
    depends_on:
      - redis
      # - web # Removing 'web' dependency for worker as it's not strictly necessary and can sometimes complicate startup order. Worker only needs Redis.
    restart: unless-stopped

volumes:
  redis_data:
